baseURL = "https://www.thesoilfactory.org"
languageCode = "en-us"
title = "The Soil Factory"
disableKinds = ["taxonomy"]
enableRobotsTXT = "true"
summaryLength = 30
copyright = "WEAVE Community Inc."
[params]
  description = "Exploring Art, Science, and Sustainability"
  paypal = "https://www.paypal.com/donate/?hosted_button_id=7MRNCBDV37CCG"
  contact = "soilfactoryevents@gmail.com"
  subscribe = "https://groups.google.com/g/soil-factory-network"
  copyrighturl = "https://weavecommunity.org"
[menus]
  [[menus.main]]
    name = 'Activities'
    pageRef = '/activities'
    weight = 10
  [[menus.main]]
    name = 'Calendar'
    pageRef = '/calendar'
    weight = 20
  [[menus.main]]
    name = 'Donors'
    pageRef = '/donors'
    weight = 30